[project]
name = ""
version = "0.0.1"
requires-python = "~=3.13"
dependencies = [
    "requests",
    "feedgenerator",
    "jinja2>=3.1.6",
    "beautifulsoup4>=4.13.4",
]

[dependency-groups]
dev = []

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
